In [1]:
import pandas as pd

df = pd.read_csv('./data/covid19_casos_brasil.csv')

In [2]:
df.head()

,city,city_ibge_code,date,epidemiological_week,estimated_population_2019,is_last,is_repeated,last_available_confirmed,last_available_confirmed_per_100k_inhabitants,last_available_date,last_available_death_rate,last_available_deaths,order_for_place,place_type,state,new_confirmed,new_deaths
0,São Paulo,3550308.0,2020-02-25,9,12252023.0,False,False,1,0.00816,2020-02-25,0.0,0,1,city,SP,1,0
1,NaN,35.0,2020-02-25,9,45919049.0,False,False,1,0.00218,2020-02-25,0.0,0,1,state,SP,1,0
2,São Paulo,3550308.0,2020-02-26,9,12252023.0,False,False,1,0.00816,2020-02-26,0.0,0,2,city,SP,0,0
3,NaN,35.0,2020-02-26,9,45919049.0,False,False,1,0.00218,2020-02-26,0.0,0,2,state,SP,0,0
4,São Paulo,3550308.0,2020-02-27,9,12252023.0,False,False,1,0.00816,2020-02-27,0.0,0,3,city,SP,0,0

In [3]:
filtro = df['city'] == 'Curitiba'
filtroNumeroCasos = df['new_confirmed'] > 250
dfFiltrado = df[filtroNumeroCasos]

dfFiltrado[(dfFiltrado['city'] != 'São Paulo') & (dfFiltrado['city'].notnull())].head(20)

,city,city_ibge_code,date,epidemiological_week,estimated_population_2019,is_last,is_repeated,last_available_confirmed,last_available_confirmed_per_100k_inhabitants,last_available_date,last_available_death_rate,last_available_deaths,order_for_place,place_type,state,new_confirmed,new_deaths
13726,Rio de Janeiro,3304557.0,2020-04-13,16,6718903.0,False,False,2322,34.55921,2020-04-13,0.0495,115,39,city,RJ,326,9
17941,Fortaleza,2304400.0,2020-04-17,16,2669342.0,False,False,2300,86.16356,2020-04-17,0.0517,119,33,city,CE,259,24
18575,Rio de Janeiro,3304557.0,2020-04-17,16,6718903.0,False,False,2946,43.84644,2020-04-17,0.0743,219,43,city,RJ,287,24
19277,Fortaleza,2304400.0,2020-04-18,16,2669342.0,False,False,2562,95.97871,2020-04-18,0.0550,141,34,city,CE,262,22
24424,Rio de Janeiro,3304557.0,2020-04-21,17,6718903.0,False,False,3587,53.38669,2020-04-21,0.0789,283,47,city,RJ,344,26
25216,Fortaleza,2304400.0,2020-04-22,17,2669342.0,False,False,3303,123.73836,2020-04-22,0.0572,189,38,city,CE,285,13
26656,Manaus,1302603.0,2020-04-23,17,2182763.0,False,False,2286,104.72965,2020-04-23,0.0844,193,42,city,AM,328,21
26833,Fortaleza,2304400.0,2020-04-23,17,2669342.0,False,False,3791,142.02002,2020-04-23,0.0559,212,39,city,CE,488,23
27663,Rio de Janeiro,3304557.0,2020-04-23,17,6718903.0,False,False,4027,59.93538,2020-04-23,0.0800,322,49,city,RJ,371,19
28524,Fortaleza,2304400.0,2020-04-24,17,2669342.0,False,False,4063,152.20980,2020-04-24,0.0561,228,40,city,CE,272,16
29127,Importados/Indefinidos,NaN,2020-04-24,17,NaN,False,False,971,NaN,2020-04-24,0.0010,1,42,city,PE,959,0
30299,Fortaleza,2304400.0,2020-04-25,17,2669342.0,False,False,4541,170.11683,2020-04-25,0.0570,259,41,city,CE,478,31
31202,Rio de Janeiro,3304557.0,2020-04-25,17,6718903.0,False,False,4481,66.69243,2020-04-25,0.0819,367,51,city,RJ,390,20
32139,Fortaleza,2304400.0,2020-04-26,18,2669342.0,False,False,4991,186.97492,2020-04-26,0.0591,295,42,city,CE,450,36
32832,Recife,2611606.0,2020-04-26,18,1645727.0,False,False,2722,165.39803,2020-04-26,0.0669,182,46,city,PE,946,18
34045,Fortaleza,2304400.0,2020-04-27,18,2669342.0,False,False,5326,199.52483,2020-04-27,0.0593,316,43,city,CE,335,21
35020,Rio de Janeiro,3304557.0,2020-04-27,18,6718903.0,False,False,5261,78.30147,2020-04-27,0.0770,405,53,city,RJ,763,23
37047,Rio de Janeiro,3304557.0,2020-04-28,18,6718903.0,False,False,5554,82.66230,2020-04-28,0.0821,456,54,city,RJ,293,51
38398,São Luís,2111300.0,2020-04-29,18,1101884.0,False,False,2432,220.71289,2020-04-29,0.0613,149,41,city,MA,283,13
38884,Recife,2611606.0,2020-04-29,18,1645727.0,False,False,3423,207.99318,2020-04-29,0.0689,236,49,city,PE,265,17

In [4]:
dfTrab = df[df['city'].isin(['Curitiba', 'Rio', 'Fortaleza', 'São Luiz', 'Recife'])]

dfTrab

,city,city_ibge_code,date,epidemiological_week,estimated_population_2019,is_last,is_repeated,last_available_confirmed,last_available_confirmed_per_100k_inhabitants,last_available_date,last_available_death_rate,last_available_deaths,order_for_place,place_type,state,new_confirmed,new_deaths
114,Recife,2611606.0,2020-03-12,11,1645727.0,False,False,2,0.12153,2020-03-12,0.0000,0,1,city,PE,2,0
116,Curitiba,4106902.0,2020-03-12,11,1933105.0,False,False,5,0.25865,2020-03-12,0.0000,0,1,city,PR,5,0
151,Recife,2611606.0,2020-03-13,11,1645727.0,False,False,2,0.12153,2020-03-13,0.0000,0,2,city,PE,0,0
153,Curitiba,4106902.0,2020-03-13,11,1933105.0,False,False,5,0.25865,2020-03-13,0.0000,0,2,city,PR,0,0
194,Recife,2611606.0,2020-03-14,11,1645727.0,False,False,6,0.36458,2020-03-14,0.0000,0,3,city,PE,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346950,São Luiz,1400605.0,2020-07-11,28,7986.0,True,False,101,1264.71325,2020-07-11,0.0099,1,86,city,RR,14,0
349210,Fortaleza,2304400.0,2020-07-12,29,2669342.0,True,False,38127,1428.32953,2020-07-12,0.0917,3498,119,city,CE,88,0
351343,Recife,2611606.0,2020-07-12,29,1645727.0,False,True,22749,1382.30703,2020-07-11,0.0864,1966,123,city,PE,0,0
351700,Curitiba,4106902.0,2020-07-12,29,1933105.0,False,True,8431,436.13772,2020-07-10,0.0249,210,123,city,PR,0,0
352322,São Luiz,1400605.0,2020-07-12,29,7986.0,False,True,101,1264.71325,2020-07-11,0.0099,1,87,city,RR,0,0

In [5]:
casos_covid = dfTrab[['date', 'epidemiological_week', 'last_available_date', 'is_last', 'is_repeated', 'last_available_confirmed', 'last_available_confirmed_per_100k_inhabitants', 'last_available_death_rate', 'last_available_deaths', 'new_confirmed', 'new_deaths']]

localizacao = dfTrab[['city', 'city_ibge_code', 'estimated_population_2019', 'order_for_place', 'place_type', 'state']]

casos_covid.head()
#localizacao.head()

,date,epidemiological_week,last_available_date,is_last,is_repeated,last_available_confirmed,last_available_confirmed_per_100k_inhabitants,last_available_death_rate,last_available_deaths,new_confirmed,new_deaths
114,2020-03-12,11,2020-03-12,False,False,2,0.12153,0.0,0,2,0
116,2020-03-12,11,2020-03-12,False,False,5,0.25865,0.0,0,5,0
151,2020-03-13,11,2020-03-13,False,False,2,0.12153,0.0,0,0,0
153,2020-03-13,11,2020-03-13,False,False,5,0.25865,0.0,0,0,0
194,2020-03-14,11,2020-03-14,False,False,6,0.36458,0.0,0,4,0

In [6]:
casos_covid.dtypes
#localizacao.columns()

date                                              object
epidemiological_week                               int64
last_available_date                               object
is_last                                             bool
is_repeated                                         bool
last_available_confirmed                           int64
last_available_confirmed_per_100k_inhabitants    float64
last_available_death_rate                        float64
last_available_deaths                              int64
new_confirmed                                      int64
new_deaths                                         int64
dtype: object

In [10]:
casos_covid = casos_covid.astype({
    'last_available_death_rate': 'str',
    'is_last':'int64',
    'is_repeated':'int64'
    })

casos_covid.dtypes

date                                              object
epidemiological_week                               int64
last_available_date                               object
is_last                                            int64
is_repeated                                        int64
last_available_confirmed                           int64
last_available_confirmed_per_100k_inhabitants    float64
last_available_death_rate                         object
last_available_deaths                              int64
new_confirmed                                      int64
new_deaths                                         int64
dtype: object